name: Welcome

on:
  issues:
    types:
      - opened

jobs:
  greeting:
    if: github.repository == 'WebGoat/WebGoat'
    runs-on: ubuntu-latest
   steps:
  - name: Run Dastardly Action Step
    uses: PortSwigger/dastardly-github-action@main
    with:
      target-url: 'https://ginandjuice.shop'
